### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by svenstaro** [dr-duplo/python-fints-url#1]
https://www.hbci-zka.de/ is now completely different. Any way to make this work again?

**Comment by dr-duplo** [comment]
Mhhh. That's not so good. Seems like they now hide the bank information behind a registration wall. I may switch to a db based approach like [fints-institute-db](https://github.com/jhermsmeier/fints-institute-db). Stay tuned or feel free to make a pull request.

**Comment by TimDaub** [comment]
Any updates? Otherwise maybe mark this repo as unmaintained?

**Comment by dr-duplo** [comment]
Just released a new working version.
